language: go
go:
  - 1.9.x
  - 1.10.x
env:
  - GOARCH=amd64 TEST_RACE=false
  - GOARCH=amd64 TEST_RACE=true
  - GOARCH=386 TEST_RACE=false
  - GOARCH=386 TEST_RACE=true
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
install:
  - export CXX="g++-4.9" CC="gcc-4.9"
  - sudo apt-get install libsnappy1 libsnappy-dev
  - git clone https://github.com/absolute8511/rocksdb.git /tmp/rocksdb
  - pushd /tmp/rocksdb && git checkout v5.18-patched && USE_SSE=1 make static_lib && popd
script:
  - CGO_CFLAGS="-I/tmp/rocksdb/include" CGO_LDFLAGS="-L/tmp/rocksdb -lrocksdb -lstdc++ -lm -lsnappy -lrt" go get github.com/youzan/gorocksdb 
  - CGO_CFLAGS="-I/tmp/rocksdb/include" CGO_LDFLAGS="-L/tmp/rocksdb -lrocksdb -lstdc++ -lm -lsnappy -lrt" go install -race github.com/youzan/gorocksdb 
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm > gpm
  - chmod +x gpm
  - wget -c https://github.com/coreos/etcd/releases/download/v2.3.8/etcd-v2.3.8-linux-amd64.tar.gz
  - tar -xvzf etcd-v2.3.8-linux-amd64.tar.gz
  - ./etcd-v2.3.8-linux-amd64/etcd -name=test-etcd0 -initial-advertise-peer-urls=http://127.0.0.1:2380 -listen-client-urls=http://127.0.0.1:2379 -advertise-client-urls=http://127.0.0.1:2379 -listen-peer-urls=http://127.0.0.1:2380 -initial-cluster="test-etcd0=http://127.0.0.1:2380" -initial-cluster-state=new --data-dir ./test-etcd > etcd.log 2>&1 &
  - go get -u golang.org/x/sys/... || true
  - dep ensure
  - ROCKSDB=/tmp/rocksdb ./test.sh
notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
