language: go
go:
  - 1.13.x
env:
  - GOARCH=amd64 TEST_RACE=false
  - GOARCH=amd64 TEST_RACE=true
  - GOARCH=386 TEST_RACE=false
  - GOARCH=386 TEST_RACE=true
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
install:
  - export CXX="g++-4.9" CC="gcc-4.9"
  - sudo apt-get install libsnappy1v5 libsnappy-dev libjemalloc1 libjemalloc-dev
  - git clone https://github.com/absolute8511/rocksdb.git /tmp/rocksdb
  - pushd /tmp/rocksdb && git checkout v6.4.6-patched && PORTABLE=1 WITH_JEMALLOC_FLAG=1 JEMALLOC=1 make static_lib && popd
script:
  - wget -c https://github.com/coreos/etcd/releases/download/v2.3.8/etcd-v2.3.8-linux-amd64.tar.gz
  - tar -xvzf etcd-v2.3.8-linux-amd64.tar.gz
  - ./etcd-v2.3.8-linux-amd64/etcd -name=test-etcd0 -initial-advertise-peer-urls=http://127.0.0.1:2380 -listen-client-urls=http://127.0.0.1:2379 -advertise-client-urls=http://127.0.0.1:2379 -listen-peer-urls=http://127.0.0.1:2380 -initial-cluster="test-etcd0=http://127.0.0.1:2380" -initial-cluster-state=new --data-dir ./test-etcd > etcd.log 2>&1 &
  - ROCKSDB=/tmp/rocksdb ./test.sh
notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
